### ISSUE TITLE
AttributeError: 'OctolapseConsoleHandler' object has no attribute '_executor'

### ISSUE THREAD

**Issue by Looking4OffSwitch** [jneilliii/OctoPrint-Python3PluginCompatibilityCheck#3]
I run into the following error while running `upgrade.py`. `python -V` returns 3.7.3.
The upgrade seems to complete but I cannot connect to the server from my browser (clicking on the Connect button eventually times out).

```
pi@octopi:~ $ python3 upgrade.py
OctoPrint Upgrade to Py 3 (v2.1.1)

Hello!
This script will move your existing OctoPrint configuration from Python 2 to Python 3
This script requires an internet connection and it will disrupt any ongoing print jobs.

It will install the latest version of OctoPrint (1.4.2) and all plugins.
No configuration or other files will be overwritten

Press [enter] to continue or ctrl-c to quit

Detecting system info...
OctoPi version: 0.17.0
Getting OctoPrint version...
OctoPrint version: 1.4.2
Reading installed plugins...
2020-09-14 11:56:28,864 - octolapse.__init__ - INFO - Release mode detected.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1676, in shutdown
    h.close()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/logging/handlers.py", line 32, in close
    self._executor.shutdown(wait=True)
AttributeError: 'OctolapseConsoleHandler' object has no attribute '_executor'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1676, in shutdown
    h.close()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/logging/handlers.py", line 32, in close
    self._executor.shutdown(wait=True)
AttributeError: 'OctolapseConsoleHandler' object has no attribute '_executor'
```

**Comment by jneilliii** [comment]
You might want to report this on the official upgrade script repo, this plugin has nothing to do with the upgrade process. I'm sure @cp2004 would want to know.

**Comment by cp2004** [comment]
@jneilliii I've reported it to OctoLapse already, it's something in its CLI handlers when I try and read it. No functional difference, the upgrade continues. There's an issue on my repo that says don't worry...
